# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys

def configParser(fileName, config):
    with open(fileName, 'r') as f:
        for line in f:
            if (not (line[0] == '#')):
                (key, sep, val) = line.partition('=')
                if (not (len(sep) == 0)):
                    val = val.strip()
                    config[key.strip()] = (int(val) if str.isdecimal(val) else val)
    print(config)

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        print('Starting main')
        fileName = sys.argv[1]
        config = {}
        configParser(fileName, config)
